### ISSUE TITLE
Pantalla Combate

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A2-2024-H1-Equipo4#6]
![image](https://github.com/unlam-tec-movil/A2-2024-H1-Equipo4/assets/5816687/47df3ff1-dd60-432f-8d6e-77f1b99f7ebb)

**Comment by Dangerous875** [comment]
![Image](https://github.com/unlam-tec-movil/A2-2024-H1-Equipo4/assets/142945807/f081f57e-f5a2-4f6d-8520-1f6b3ef42aa2)
